name: Check WordPress Plugin SVN Updates For CF7 And Addons

on:
  push:
    branches:
      - bug-fix
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  check-svn-updates:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        plugin:
          - simple-cloudflare-turnstile
          - wpforms-lite
          - akismet
          # Add more plugins here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SVN
        run: sudo apt-get install -y subversion

      - name: Check for latest SVN revision
        id: check-svn
        run: |
          plugin_name=${{ matrix.plugin }}
          svn info https://plugins.svn.wordpress.org/$plugin_name/trunk | grep 'Last Changed Rev' | awk '{print $4}' > ".revision/${plugin_name}_current_revision_wpforms.txt"

      - name: Get previous SVN revision
        id: get-previous
        run: |
          plugin_name=${{ matrix.plugin }}
          if [ -f ".revision/${plugin_name}_latest_revision_wpforms.txt" ]; then
            cat ".revision/${plugin_name}_latest_revision_wpforms.txt"
          else
            echo "0"
          fi
        continue-on-error: true

      - name: Compare revisions
        id: compare-revisions
        run: |
          plugin_name=${{ matrix.plugin }}
          current_revision=$(cat ".revision/${plugin_name}_current_revision_wpforms.txt")
          
          # Check if the previous revision file exists
          if [ -f ".revision/${plugin_name}_latest_revision_wpforms.txt" ]; then
            previous_revision=$(cat ".revision/${plugin_name}_latest_revision_wpforms.txt")
          else
            previous_revision="0"
          fi

          echo "Current revision: $current_revision"
          echo "Previous revision: $previous_revision"

          if [ "$current_revision" -gt "$previous_revision" ]; then
            echo "${plugin_name}_update_found=true" >> $GITHUB_ENV
            echo "current_revision=$current_revision" >> $GITHUB_ENV
            echo "::set-output name=${plugin_name}_update_found::true"
          else
            echo "${plugin_name}_update_found=false" >> $GITHUB_ENV
            echo "::set-output name=${plugin_name}_update_found::false"
          fi

      - name: Save current revision as latest revision
        if: steps.compare-revisions.outputs.${{ matrix.plugin }}_update_found == 'true'
        run: |
          plugin_name=${{ matrix.plugin }}
          mkdir -p .revision
          cp ".revision/${plugin_name}_current_revision_wpforms.txt" ".revision/${plugin_name}_latest_revision_wpforms.txt"

      - name: Commit updated revision file
        if: steps.compare-revisions.outputs.${{ matrix.plugin }}_update_found == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          plugin_name=${{ matrix.plugin }}
          git pull --rebase origin bug-fixes
          git add ".revision/${plugin_name}_latest_revision_wpforms.txt"
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update $plugin_name SVN revision"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Create WPFRORMS Trusntile Natvie for Testing in InstaWP
        if: steps.compare-revisions.outputs.wpforms-lite_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG:  wpforms--cloudflare-turnstile-native
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template

      - name: Create CF7 & hCaptcha native Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.wpforms-lite_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: wpforms--hcaptcha-native
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template

      - name: Create WPFRORMS Trusntile for Testing in InstaWP
        if: ${{ ( steps.compare-revisions.outputs.wpforms-lite_update_found == 'true' ) || ( steps.compare-revisions.outputs.simple-cloudflare-turnstile_update_found == 'true' ) }}
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: wpforms--simple-cloudflare-turnstile
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template

      - name: Create CF7 With ReCaptcha v2 Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.wpforms-lite_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: wpforms--google-recaptcha-v2
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template
      - name: Create CF7 With Akismet Site for Testing in InstaWP
        if: ${{ ( steps.compare-revisions.outputs.wpforms-lite_update_found  ) || ( steps.compare-revisions.outputs.akismet== 'true' ) }}
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: wpforms--akismet-anti-spam-plugin
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template

      - name: Create CF7 Pro Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.wpforms-lite_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: wpforms-pro
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template

      - name: Create CF7 With ReCaptcha v3 Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.wpforms-lite_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: wpforms--google-recaptcha-v3-native
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template
      - name: Create CF7 Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.wpforms-lite_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: wp-forms
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template