name: Check WordPress Plugin Version Updates

on:
  push:
    branches:
      - stagings
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  check-plugin-version:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        plugin:
          - simple-cloudflare-turnstile
          - wpforms-lite
          - akismet
          - gravityforms
          # Add more plugins here

    steps:
      - name: Get plugin version from WordPress site
        id: get-plugin-version
        run: |
          plugin_slug=${{ matrix.plugin }}
          response=$(curl -s "https://your-wordpress-site.com/wp-json/checkview/v1/plugin-version?_plugin_slug=$plugin_slug")
          plugin_version=$(echo $response | jq -r '.version')

          if [ "$plugin_version" == "null" ] || [ -z "$plugin_version" ]; then
            echo "Plugin version not found for $plugin_slug"
            exit 1
          else
            echo "Plugin version for $plugin_slug is $plugin_version"
            echo "::set-output name=plugin_version::$plugin_version"
            # Save the plugin version to the current revision file
            current_revision_file=".revision/${plugin_name}_current_revision_gravityforms.txt"
            echo "$plugin_version" > "$current_revision_file"
          fi

      - name: Get previous plugin version
        id: get-previous
        run: |
          plugin_name=${{ matrix.plugin }}
          if [ -f ".revision/${plugin_name}_latest_revision_gravityforms.txt" ]; then
            cat ".revision/${plugin_name}_latest_revision_gravityforms.txt"
          else
            echo "0"
          fi
        continue-on-error: true

      - name: Compare revisions
        id: compare-revisions
        run: |
          plugin_name=${{ matrix.plugin }}
          current_revision=$(cat ".revision/${plugin_name}_current_revision_gravityforms.txt")
          
          # Check if the previous revision file exists
          if [ -f ".revision/${plugin_name}_latest_revision_gravityforms.txt" ]; then
            previous_revision=$(cat ".revision/${plugin_name}_latest_revision_gravityforms.txt")
          else
            previous_revision="0"
          fi

          echo "Current revision: $current_revision"
          echo "Previous revision: $previous_revision"

          if [ "$current_revision" -gt "$previous_revision" ]; then
            echo "${plugin_name}_update_found=true" >> $GITHUB_ENV
            echo "::set-output name=${plugin_name}_update_found::true"
          else
            echo "${plugin_name}_update_found=false" >> $GITHUB_ENV
            echo "::set-output name=${plugin_name}_update_found::false"
          fi

      - name: Save current revision as latest revision
        if: steps.compare-revisions.outputs.${{ matrix.plugin }}_update_found == 'true'
        run: |
          plugin_name=${{ matrix.plugin }}
          mkdir -p .revision
          cp ".revision/${plugin_name}_current_revision_gravityforms.txt" ".revision/${plugin_name}_latest_revision_gravityforms.txt"

      - name: Commit updated revision file
        if: steps.compare-revisions.outputs.${{ matrix.plugin }}_update_found == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          plugin_name=${{ matrix.plugin }}
          # Stash any unstaged changes to avoid conflicts during pull
          git stash --include-untracked
    
          # Pull the latest changes from the remote branch with rebase
          git pull --rebase origin main

          # Apply the stashed changes back after the pull
          git stash pop || echo "No changes to apply from stash"
          git add ".revision/${plugin_name}_latest_revision_gravityforms.txt"
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update $plugin_name SVN revision"
            git push
          else
            echo "No changes to commit"
          fi
            
      - name: Create Gravity Forms & hCaptcha native Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.gravityforms_update_found == 'true' 
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: gravity-forms--hcaptcha-for-wp
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template

      - name: Create Gravity Forms Trusntile for Testing in InstaWP
        if: ${{ ( steps.compare-revisions.outputs.gravityforms_update_found == 'true' ) || ( steps.compare-revisions.outputs.simple-cloudflare-turnstile_update_found == 'true' ) }}
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: gravity-forms--simple-cloudflare-turnstile
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template

      - name: Create FluentForms Trusntile Natvie for Testing in InstaWP
        if: steps.compare-revisions.outputs.gravityforms_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG:  gravity-forms--cloudflare-turnstile-native
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template
            
      - name: Create Gravity Forms With Akismet Site for Testing in InstaWP
        if: ${{ ( steps.compare-revisions.outputs.gravityforms_update_found == 'true' ) || ( steps.compare-revisions.outputs.akismet_update_found== 'true' ) }}
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: gravity-forms--akismet-anti-spam
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template

      - name: Create Gravity Forms With ReCaptcha v3 Native Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.gravityforms_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: gravity-forms--recaptcha-v3-native
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template


      - name: Create Gravity Forms Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.gravityforms_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: gravity-forms
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template