name: InstaWP WordPress Testing For CheckView

on:
  push:
    branches:
      - main

  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  create-wp-for-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: instawp/wordpress-testing-automation@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          INSTAWP_TEMPLATE_SLUG: checkview-testing
          REPO_ID: 509
          EXPIRY_HOURS: 1
          INSTAWP_ACTION: create-site-template