name: Check WordPress Plugin SVN Updates For Ninja Forms And Addons

on:
  push:
    branches:
      - bug-fixes
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  check-svn-updates:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        plugin:
          - ninja-forms
          - hcaptcha-for-forms-and-more
          - akismet
          # Add more plugins here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SVN
        run: sudo apt-get install -y subversion

      - name: Check for latest SVN revision
        id: check-svn
        run: |
          plugin_name=${{ matrix.plugin }}
          svn info https://plugins.svn.wordpress.org/$plugin_name/trunk | grep 'Last Changed Rev' | awk '{print $4}' > ".revision/${plugin_name}_current_revision_ninja-forms.txt"

      - name: Get previous SVN revision
        id: get-previous
        run: |
          plugin_name=${{ matrix.plugin }}
          if [ -f ".revision/${plugin_name}_latest_revision_ninja-forms.txt" ]; then
            cat ".revision/${plugin_name}_latest_revision_ninja-forms.txt"
          else
            echo "0"
          fi
        continue-on-error: true

      - name: Compare revisions
        id: compare-revisions
        run: |
          plugin_name=${{ matrix.plugin }}
          current_revision=$(cat ".revision/${plugin_name}_current_revision_ninja-forms.txt")
          
          # Check if the previous revision file exists
          if [ -f ".revision/${plugin_name}_latest_revision_ninja-forms.txt" ]; then
            previous_revision=$(cat ".revision/${plugin_name}_latest_revision_ninja-forms.txt")
          else
            previous_revision="0"
          fi

          echo "Current revision: $current_revision"
          echo "Previous revision: $previous_revision"

          if [ "$current_revision" -gt "$previous_revision" ]; then
            echo "${plugin_name}_update_found=true" >> $GITHUB_ENV
            echo "current_revision=$current_revision" >> $GITHUB_ENV
            echo "::set-output name=${plugin_name}_update_found::true"
          else
            echo "${plugin_name}_update_found=false" >> $GITHUB_ENV
            echo "::set-output name=${plugin_name}_update_found::false"
          fi

      - name: Save current revision as latest revision
        if: steps.compare-revisions.outputs.${{ matrix.plugin }}_update_found == 'true'
        run: |
          plugin_name=${{ matrix.plugin }}
          mkdir -p .revision
          cp ".revision/${plugin_name}_current_revision_ninja-forms.txt" ".revision/${plugin_name}_latest_revision_ninja-forms.txt"

      - name: Commit updated revision file
        if: steps.compare-revisions.outputs.${{ matrix.plugin }}_update_found == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          plugin_name=${{ matrix.plugin }}
          # Stash any unstaged changes to avoid conflicts during pull
          git stash --include-untracked
    
          # Pull the latest changes from the remote branch with rebase
          git pull --rebase origin bug-fixes

          # Apply the stashed changes back after the pull
          git stash pop || echo "No changes to apply from stash"
          git add ".revision/${plugin_name}_latest_revision_ninja-forms.txt"
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update $plugin_name SVN revision"
            git push
          else
            echo "No changes to commit"
          fi
      - name: Create Ninja Forms & hCaptcha Site for Testing in InstaWP
        if: ${{ ( steps.compare-revisions.outputs.ninja-forms_update_found == 'true' ) || ( steps.compare-revisions.outputs.hcaptcha-for-forms-and-more_update_found == 'true' ) }}
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: ninja-forms--hcaptcha-for-wp
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template

            
      - name: Create Ninja Forms With Akismet Site for Testing in InstaWP
        if: ${{ ( steps.compare-revisions.outputs.ninja-forms_update_found == 'true' ) || ( steps.compare-revisions.outputs.akismet_update_found== 'true' ) }}
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: ninja-forms--akismet-anti-spam-plugin
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template

      - name: Create Ninja Forms With ReCaptcha v3 Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.ninja-forms_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: ninja-forms--recaptcha-v3
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template

      - name: Create Ninja Forms With ReCaptcha v2 Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.ninja-forms_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: ninja-forms--google-recaptcha-v2
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template
            
      - name: Create Ninja Forms Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.ninja-forms_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: ninja-forms
            REPO_ID: 521
            EXPIRY_HOURS: 1
            INSTAWP_ACTION: create-site-template