name: Check WordPress Plugin SVN Updates For WooCommerce And Addons

on:
  push:
    branches:
      - bug-fixes
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  check-svn-updates:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        plugin:
          - simple-cloudflare-turnstile
          - woocommerce
          - hcaptcha-for-forms-and-more
          # Add more plugins here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SVN
        run: sudo apt-get install -y subversion

      - name: Check for latest SVN revision
        id: check-svn
        run: |
          plugin_name=${{ matrix.plugin }}
          svn info https://plugins.svn.wordpress.org/$plugin_name/trunk | grep 'Last Changed Rev' | awk '{print $4}' > "${plugin_name}_current_revision.txt"

      - name: Get previous SVN revision
        id: get-previous
        run: |
          plugin_name=${{ matrix.plugin }}
          if [ -f "${plugin_name}_previous_revision.txt" ]; then
            cat "${plugin_name}_previous_revision.txt"
          else
            echo "0" > "${plugin_name}_previous_revision.txt"
          fi
        continue-on-error: true

      - name: Compare revisions
        id: compare-revisions
        run: |
          plugin_name=${{ matrix.plugin }}
          current_revision=$(cat "${plugin_name}_current_revision.txt")
          previous_revision=$(cat "${plugin_name}_previous_revision.txt")

          echo "Current revision: $current_revision"
          echo "Previous revision: $previous_revision"

          if [ "$current_revision" -gt "$previous_revision" ]; then
            echo "${plugin_name}_update_found=true" >> $GITHUB_ENV
            echo "current_revision=$current_revision" >> $GITHUB_ENV
            echo "::set-output name=${plugin_name}_update_found::true"
          else
            echo "${plugin_name}_update_found=false" >> $GITHUB_ENV
            echo "::set-output name=${plugin_name}_update_found::false"
          fi

      - name: Save current revision as previous revision
        if: steps.compare-revisions.outputs.${{ matrix.plugin }}_update_found == 'true'
        run: |
          plugin_name=${{ matrix.plugin }}
          cp "${plugin_name}_current_revision.txt" "${plugin_name}_previous_revision.txt"

      - name: Commit updated revision file
        if: steps.compare-revisions.outputs.${{ matrix.plugin }}_update_found == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          plugin_name=${{ matrix.plugin }}
          git add "${plugin_name}_previous_revision.txt"
          git commit -m "Update $plugin_name SVN revision"
          git push
      - name: Create WOO Trusntile for Testing in InstaWP
        if: ${{ ( steps.compare-revisions.outputs.woocommerce_update_found == 'true' ) || ( steps.compare-revisions.outputs.simple-cloudflare-turnstile_update_found == 'true' ) }}
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: woo-classic---simple-cloudflare-turnstile
            REPO_ID: 521
            INSTAWP_ACTION: create-site-template

      - name: Create WOO Blocks Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.woocommerce_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: woo-blocks
            REPO_ID: 521
            INSTAWP_ACTION: create-site-template


      - name: Create WOO Classic Site for Testing in InstaWP
        if: steps.compare-revisions.outputs.woocommerce_update_found == 'true'
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: woo-classic
            REPO_ID: 521
            INSTAWP_ACTION: create-site-template

      - name: Create WOO Blocks With hCaptcha Site for Testing in InstaWP
        if: ${{ ( steps.compare-revisions.outputs.woocommerce_update_found == 'true' ) || ( steps.compare-revisions.outputs.woo-blocks--hcaptcha-for-wp_update_found == 'true' ) }}
        uses: instawp/wordpress-testing-automation@main
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
            INSTAWP_TEMPLATE_SLUG: woo-blocks--hcaptcha-for-wp
            REPO_ID: 521
            INSTAWP_ACTION: create-site-template

